### PR TITLE
Update tilt.md and relayer.md

### PR DESCRIPTION
**Pull request by Kunj125**
fixed several typos and grammatical errors

### CODE REVIEW

**Review by Kunj125 — COMMENTED** [review]
I am not sure whether the line 33 in wlv.md should be 'guardian' or 'guardiand'

**Comment by evan-gray** [comment]
Hi @Kunj125, thanks for the PRs. It looks like this one has some conflicts after merging the other PRs, if there are still changes to be made after you rebase and resolve conflicts, then reopen this.

**Comment by evan-gray** [comment]
> I am not sure whether the line 33 in wlv.md should be 'guardian' or 'guardiand'

I believe all of the uses in the document are correct. `guardiand` is the service / executable for running the guardian node.

**Comment by Kunj125** [comment]
> I believe all of the uses in the document are correct. `guardiand` is the service / executable for running the guardian node.
Thanks for the clarification, Evan!

**Pull request closed without merging**
