### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tanmaybhatcodinggenius**
You silly goose, you misspelled your own name. Can't believe I had to quit being a comedian, take up a new career just to come fix this for you. Money please. 50K USD minimum. Thanks. Love you Kanav.

### CODE REVIEW

**Comment by kcsongor** [comment]
Great patch! 🫣

**Review by kcsongor — APPROVED** [review]

**Review by kcsongor — APPROVED** [review]

**Comment by SwayStar123** [comment]
>tanmay bhat became a wormhole contributor before I did

**Comment by shubhsharma19** [comment]
Wah 🔥👀

**Comment by viv1dixit** [comment]
kudos to tanmay bhaiya 🔥

**Comment by shr-p** [comment]
getting introduced to GitHub by TB🔥

**Comment by shyamtawli** [comment]
Welcome to Open Source @tanmaybhatcodinggenius

**Comment by ayushya0612** [comment]
kudos to @tanmaybhatcodinggenius 
👅

**Comment by anipaul2** [comment]
The fact that the pr got merged makes it even more funnier. @tanmaybhatcodinggenius more contributions ser.

**Comment by JatinSharma32** [comment]
merged 😎

**Comment by ronisarkarexe** [comment]
Great

**Comment by binayaksadangi** [comment]
Small role huge impact ft. Tanmay Bhat

**Comment by 1010nishant** [comment]
I want this to become a standard commit style.

**Comment by adarshpriyadarshii** [comment]
bot army raid !

**Comment by prakhartiwari0** [comment]
Sup @shubhsharma19

**Comment by shubhsharma19** [comment]
Haha you found me here too 😂 @prakhartiwari0

**Comment by Chatro-League** [comment]
TanmayBhat has more open source contributions than I have and this makes me feel sad and happy at the same time

**Comment by prakhartiwari0** [comment]
@shubhsharma19 and on YouTube comments too 😛 just didn't replied there due to laziness

**Comment by Arthavruksha** [comment]
This is INSANE

**Comment by kwatraakshay** [comment]
crazy af

**Comment by b17saurabh** [comment]
It's accepted 👍

**Comment by Omkar0104** [comment]
@tanmaybhatcodinggenius, Not anymore Provider OP. Change it to Contributer OP

**Comment by msprajwal** [comment]
😂😂👌

**Pull request merged**
