### PR TITLE
Update 3_xdataxassets.md

### PR DESCRIPTION
**Pull request by ThisIs-Aryan**
Can't you see, what your developers write?? You are a grown up now, you should know the correct spelling of reservoir. Being a school student I figured it out. Now, I need money as a fine (at least a million dollar). As soon as I turn 18, just hire me, my grammar is much better. By the way, love you Kcsongor. 

If you find yourself free, then watch this:
https://youtu.be/kDGxKxIgADY

### CODE REVIEW

**Review by Tony-H-Stark — APPROVED** [review]
Yeah, everything is fine, thanks to @ThisIs-Aryan. I appreciate. He should be paid well!

**Review by Tony-H-Stark — APPROVED** [review]
Yeah, everything is fine, thanks to @ThisIs-Aryan. I appreciate. He should be paid well!

**Review by kcsongor — APPROVED** [review]
Solid, thanks!

**Comment by ThisIs-Aryan** [comment]
> Solid, thanks!

Welcome! But actually I need money than thanks😅

**Pull request merged**
